AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Phantasml API.

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.handler
      Runtime: nodejs8.10
      Events:
        Product:
          Type: Api
          Properties:
            Path: /api
            Method: any
