AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Phantasml API.

Resources:

  GetUserStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.getStatus
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/status
            Method: get
   
  LoginUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.login
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/login
            Method: post

  LogoutUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.logout
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/logout
            Method: post
