AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Phantasml API.

Parameters:
  
  FromEmail:
    Type: String
  
  SiteUrl:
    Type: String
  
Resources:

  GetUserStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.getStatus
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/status
            Method: get
   
  LoginUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.login
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/login
            Method: post

  LogoutUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.logout
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/logout
            Method: post

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.create
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/create
            Method: post

  UserPassword:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.password
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/password
            Method: post
