AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Phantasml API.

Parameters:
  
  Role:
    Type: String
    
  FromEmail:
    Type: String
  
  SiteUrl:
    Type: String
  
  GoogleClientId:
    Type: String
  
Resources:

  GetUserStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.getStatus
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/status
            Method: get
   
  LoginUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.login
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          SITE_URL: !Ref SiteUrl
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/login
            Method: post

  LogoutUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.logout
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/logout
            Method: post

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.create
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/create
            Method: post

  SetupUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.setup
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/setup
            Method: post
            
  UserPasswordReset:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.passwordReset
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/password_reset
            Method: post

  UserPassword:
    Type: AWS::Serverless::Function
    Properties:
      Handler: user.password
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/user/password
            Method: post

  GetAdminSettings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: admin.getSettings
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/admin/settings
            Method: get

  PutAdminSettings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: admin.putSettings
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/admin/settings
            Method: put

  AdminInvite:
    Type: AWS::Serverless::Function
    Properties:
      Handler: admin.invite
      Role: !Ref Role
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          SITE_URL: !Ref SiteUrl
      Events:
        Request:
          Type: Api
          Properties:
            Path: /api/admin/invite
            Method: post
