AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Phantasml API.

Resources:

  Sessions:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sessions.handler
      Runtime: nodejs8.10
      CodeUri: ../../build/server
      Events:
        Product:
          Type: Api
          Properties:
            Path: /api/session
            Method: any
